### ISSUE TITLE
Consider using a column definition builder

### ISSUE THREAD

**Issue by benedictjohannes** [aldy505/bob#1]
This is just a discussion, not a real "isu". 

I think your project can benefit from defining columns atomically, which is then joined using `, `  to the `CREATE TABLE` statement. 

From the official pgsql docs, 
```
CREATE [ [ GLOBAL | LOCAL ] { TEMPORARY | TEMP } | UNLOGGED ] TABLE [ IF NOT EXISTS ] table_name ( [
  { column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
    | table_constraint
    | LIKE source_table [ like_option ... ] }
    [, ... ]
] )
```
For the column definition:
1. Each columns must contain name, type
2. Optionally can contain null/not null or unique keywords

Thus you can create a 
```go
type ColumnDef {
  name string
  type string
  extras []string
}
```
With this you can make the table struct to have 
```go
TableDef {
  // other struct members
  columns []ColumnDef
} 
```
With which working with column constrains would be more "gampang":
```go
bob.
  CreateTable("table_name").
  StringColumn("column_1", "not null", "unique"). 
  AddColumn(ColumnDef{name:"column_2", type:"jsonb"}).
  TimeStampTzColumn("column_3", "default now()") 
```

Each table constraints (like the foreign keys) can also be handled analogous to this manner. 

Although this would be a far departure from the way your package is structured, I initiated this discussion just as using this approach might allow your package to
- add support for `alter table alter column` much more easily 
- construct the `create table` as a single SQL, eliminating the need users to range over SQL generated from your package split with `;`

**Comment by aldy505** [comment]
A very good idea, thanks! I'll work on column constraints later this week. But, I'll check on database compatibility first.
